- name: Install base packages 
  hosts: localhost
  become: true
  tasks:

    - name: Install base packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - tldr 
          - tmux


    - name: Get NodeJS 20.x Deb package
      get_url:
        url: https://deb.nodesource.com/setup_20.x 
        dest: /tmp/setup_20.x
      
    - name: Run Node setup 
      ansible.builtin.script: /tmp/setup_20.x

    - name: Install node v20.x LTS
      ansible.builtin.apt:
        pkg:
          - nodejs
