- name: Install NeoVim and Configs
  hosts: localhost
  tasks:

    - name: Install prerequisits
      become: true
      ansible.builtin.apt:
        pkg:
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl

    - name: Clone NeoVim source files
      git:
        repo: git@github.com:neovim/neovim.git
        dest: /home/tedewaard/neovim/
        clone: true
        update: true

    - name: Install NeoVim
      become: true
      shell: |
        cd /home/tedewaard/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
        make install
