- name: Install NeoVim and Configs
  hosts: localhost
  become: true
  tasks:

    - name: Install prerequisits
      ansible.builtin.apt:
        pkg:
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl

    - name: Clone NeoVim source files
      git:
        repo: https://github.com/neovim/NeoVim
        dest: /home/tedewaard/neovim/
        clone: true
        update: true

    - name: Install NeoVim
      shell: |
        cd /home/tedewaard/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
        make install
